--============================================================
-- Description:
-- This script identifies the top 10 products per category
-- based on total revenue generated, along with each
-- product's % contribution to overall revenue.
--
-- Approach:
-- - Joins fact_sales with dim_products on product_key
-- - Aggregates total revenue per product and category
-- - Uses RANK() window function partitioned by category
--   to rank products within each category by revenue
-- - Filters to top 10 ranked products per category
-- - Adds revenue contribution % using SUM() OVER()
--
-- Output columns:
-- category      : Product category name
-- product_name  : Product name
-- TotalRevenue  : Total revenue generated by that product
-- revenue_pct   : Product's % contribution to total revenue
--============================================================

WITH ProductRevenue AS (
    SELECT
        p.category,
        p.product_name,
        SUM(s.sales) AS TotalRevenue
    FROM gold.fact_sales s
    JOIN gold.dim_products p
        ON s.product_key = p.product_key
    GROUP BY
        p.category,
        p.product_name
),

RankedProducts AS (
    SELECT *,
        RANK() OVER(
            PARTITION BY category
            ORDER BY TotalRevenue DESC
        ) AS rn
    FROM ProductRevenue
)

SELECT
    category,
    product_name,
    TotalRevenue,
    ROUND(TotalRevenue * 100.0 / SUM(TotalRevenue) OVER(), 2) AS revenue_pct
FROM RankedProducts
WHERE rn <= 10
